### ISSUE TITLE
Failed to find facts from PuppetDB error

### ISSUE THREAD

**Issue by frossigneux** [pmorillon/xp5k-openstack#12]
I run a deployment from my laptop on Reims.

I get this error:

```
[command][stremi-4.reims.grid5000.fr] eatmydata /opt/puppetlabs/bin/puppet agent -t --server stremi-4.reims.grid5000.fr
[stderr][stremi-4.reims.grid5000.fr] Warning: Unable to fetch my node definition, but the agent run will continue:
[stderr][stremi-4.reims.grid5000.fr] Warning: Error 400 on SERVER: Could not retrieve facts for stremi-4.reims.grid5000.fr: Failed to find facts from PuppetDB at puppet:8140: Failed to execute '/pdb/query/v4/nodes/stremi-4.reims.grid5000.fr/facts' on at least 1 of the following 'server_urls': https://puppetdb:8081
```

Here is my xp.conf:

```
site 'reims'
walltime '08:00:00'
scenario 'liberty_multinodes_singleinterface'
computes '5'

ssh_config '/tmp/xp5k-openstack/.ssh_config'
public_key '/home/rossigneux/.ssh/id_rsa.pub'
user 'frossigneux'
```

It worked very well some month ago.

**Comment by pmorillon** [comment]
It's just a warning from puppet agent, this does not affect openstack deployment.

**Comment by frossigneux** [comment]
Yes, the deployment still continue, but when the deployment is finished, I can see Glance not found, Neutron not found, Nova not found, and Ceilometer errors too...
So there is a problem.

**Comment by pmorillon** [comment]
Yes ! i think you do not apply recent patches into your custom environment : 
- https://github.com/pmorillon/xp5k-openstack/commit/339f7e27fb310b7e3ff847d14effc0a0dad3b593
- https://github.com/pmorillon/xp5k-openstack/commit/0b151e999fe5b2c88eac9b3184f8704a3a2fd6c5
- https://github.com/pmorillon/xp5k-openstack/commit/db03e0128161f961a53afa507396f7df11b717c9

**Comment by frossigneux** [comment]
I use this scenario:
https://github.com/dgetux/liberty_multinodes_singleinterface

So I will patch it.

**Comment by pmorillon** [comment]
Thanks ! you can submit a pull request to dgetux for other users.
