### ISSUE TITLE
starter_kit wrong endpoints

### ISSUE THREAD

**Issue by asimonet** [pmorillon/xp5k-openstack#8]
In the starter_kit scenario, the endpoints all point to 127.0.0.1:<port>, which prevents remote control to work using the cli or the api from another machine.

It would be better if the endpoints pointed to the hostname, like in the multinodes scenario.

**Comment by pmorillon** [comment]
The goal of liberty_start_kit scenario is to deploy a simple instance of openstack for Grid5000 tutorial.
You can easily create your own scenario and adapts to your own use cases.
